version: '3.8'
services:
  peter-zk01:
    image: confluentinc/cp-zookeeper:latest
    hostname: peter-zk01
    container_name: peter-zk01
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '2181:2181'
    networks:
      - kafka-network

  peter-zk02:
    image: confluentinc/cp-zookeeper:latest
    hostname: peter-zk02
    container_name: peter-zk02
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '2182:2182'
    networks:
      - kafka-network

  peter-zk03:
    image: confluentinc/cp-zookeeper:latest
    hostname: peter-zk03
    container_name: peter-zk03
    environment:
      ZOOKEEPER_CLIENT_PORT: 2183
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '2183:2183'
    networks:
      - kafka-network

  peter-kafka01:
    image: confluentinc/cp-kafka:latest
    hostname: peter-kafka01
    container_name: peter-kafka01
    depends_on:
      - peter-zk01
    environment:
      KAFKA_ZOOKEEPER_CONNECT: peter-zk01:2181,peter-zk02:2182,peter-zk03:2183
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://peter-kafka01:9092
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
    ports:
      - '9092:9092'
    networks:
      - kafka-network

  peter-kafka02:
    image: confluentinc/cp-kafka:latest
    hostname: peter-kafka02
    container_name: peter-kafka02
    depends_on:
      - peter-zk02
    environment:
      KAFKA_ZOOKEEPER_CONNECT: peter-zk01:2181,peter-zk02:2182,peter-zk03:2183
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://peter-kafka02:9093
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
    ports:
      - '9093:9093'
    networks:
      - kafka-network

  peter-kafka03:
    image: confluentinc/cp-kafka:latest
    hostname: peter-kafka03
    container_name: peter-kafka03
    depends_on:
      - peter-zk03
    environment:
      KAFKA_ZOOKEEPER_CONNECT: peter-zk01:2181,peter-zk02:2182,peter-zk03:2183
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://peter-kafka03:9094
      KAFKA_BROKER_ID: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
    ports:
      - '9094:9094'
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge
