version: '3'

services:
  redis-master:
    image: redis:latest
    container_name: redis-master
    ports:
      - '6379:6379'
    volumes:
      - ./data/master:/data

  redis-slave:
    image: redis:latest
    container_name: redis-slave
    ports:
      - '6380:6379'
    command: redis-server --replicaof redis-master 6379
    depends_on:
      - redis-master
    volumes:
      - ./data/slave:/data
    networks:
      - redis-net

  sentinel:
    image: redis:latest
    container_name: redis-sentinel
    command: redis-server /etc/sentinel.conf --sentinel
    networks:
      - redis-net
    ports:
      - '26379:26379'
    volumes:
      - ./sentinel.conf:/etc/sentinel.conf
    depends_on:
      - redis-master
      - redis-slave

networks:
  redis-net:
    driver: bridge
