version: '3.7'

services:
  redis-master:
    image: redis:latest
    command: redis-server --bind 0.0.0.0
    volumes:
      - './.data:/data'
    ports:
      - 6379:6379
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  redis-slave:
    image: redis:latest
    command: redis-server --replicaof redis-master 6379 -- port 6380
    ports:
      - 6380:6380
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - './.data:/data'

  sentinel:
    container_name: redis-sentinel
    ports:
      - 26379:26379
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    build:
      context: ./redis-sentinel
    depends_on:
      - redis-master
      - redis-slave
