name: integration test

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Change directory and install dependencies
        run: |
          cd ./nestjs-laboratory
      - name: Install NPM dependencies
        run: npm install
      - name: Runs integration test suites
        run: npm run test product.module
